### ISSUE TITLE
latam - layout codes with more than two characters

### ISSUE THREAD

**Issue by juanmatias** [porras/i3-keyboard-layout#1]
Hi, and thanks for this script.

I usually switch between es, us and latam layouts. The cycle won't work due to it does not recognize the "latam" code. 

Solution is easy, in line 6 just change this:

`setxkbmap -query | grep -oP 'layout:\s*\K(\w{2})'`

to this:

`setxkbmap -query | grep -oP 'layout:\s*\K(\w{2,5})'`

It should be checked for other codes with more characters, maybe.

**Comment by porras** [comment]
Hi, thanks for the catch! I hadn't given much thought to that, since all layouts I use are 2 characters. I'll try a fix in the next days that covers for all possible values.

**Comment by porras** [comment]
The fix was simple so I just did it. It Works On My Machine (tm) but let me know if it doesn't fix it for you. Thanks!
