### ISSUE TITLE
i3bar update layout text

### ISSUE THREAD

**Issue by ilazaridis** [porras/i3-keyboard-layout#7]
Hi there,

I can change the layout using the script, but the string displayed on the i3bar isn't updated when I cycle between layouts, not even after refreshing i3. The same string is always displayed.

I am using manjaro i3.

**Comment by porras** [comment]
Hi! Can you paste the relevant fragment of your i3 config, and check the output of the `i3-keyboard-layout get` command? I'm also using Manjaro and it works fine for me :confused:

**Comment by ilazaridis** [comment]
Hi @porras,

it's like this:
```
bar {
	i3bar_command i3bar
	status_command i3status | i3-keyboard-layout i3status
	position bottom

	tray_output primary
        ...
    }
}
```

**Comment by porras** [comment]
Sorry, I can't seem to reproduce, your setup seems correct, assuming that the script is executable and in the `$PATH` :confused: 

A couple of additional things to check to try to debug:

1. Run the get subcommand in the terminal and check it returns the right value:

```
$ ./i3-keyboard-layout get
us
```

2. Run the bar command in the terminal and check it inserts it in the right place:

```
$ i3status | ./i3-keyboard-layout i3status
{"version":1}
[
[{"full_text":"us "}, ...]
,[{"full_text":"us "}, ...]
# I change the layout
,[{"full_text":"es "}, ...]
```

**Comment by ilazaridis** [comment]
Nevermind, I switched to polybar and it works fine. ;)
